name: Snyk

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '0 6 * * 5'

jobs:
  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Snyk Test
        uses: snyk/actions@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --yarn-workspaces --sarif-file-output=snyk.sarif
      - name: Snyk Monitor
        uses: snyk/actions@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --yarn-workspaces
      - name: Upload result
        uses: github/codeql-action/upload-sarif@master
        with:
          sarif_file: snyk.sarif
